### ISSUE TITLE
How do you compile it?

### ISSUE THREAD

**Issue by nathanss** [govindparmar/Win32Hello#1]
I'm trying to compile it using Visual C++ x86 Native Build Tools 

Which parameters you have to pass to "cl" for it to work? I'm a rookie at Windows development.

Thanks!

**Comment by govindparmar** [comment]
cl winmain.c /O2t /DUNICODE /D_UNICODE /link user32.lib gdi32.lib 

:)

**Comment by nathanss** [comment]
Thank you! it worked. 
Closing the issue.
